### ISSUE TITLE
ETA for: "Add the ability to set the arming / partial / night / disarm commands"

### ISSUE THREAD

**Issue by ilvolodel** [gawindx/homebridge-risco-platform#10]
Thanks for your job, is there any ETA for set the ability indicated in object?

**Comment by gawindx** [comment]
no specific date for the moment.
I will soon get back to this project, I can see if it fits in my schedule and integrate it if possible but I prefer not to promise anything.

but i think it shouldn't take too long to achieve

**Comment by gawindx** [comment]
The functionality has been added (the npm is not yet published because I still have additions to make before publication).
On the other hand, the repository is up to date and I invite you to take a look at the README and to give me a feedback if the way I integrated it seems logical to you.

I am open to discussion if this does not seem suitable to you.

**Comment by gawindx** [comment]
the npm package is updated to v1.1.6 and contains this fix.
I close the exit, do not hesitate to reopen it if necessary
