### ISSUE TITLE
Contact Sensors showing as Detectors

### ISSUE THREAD

**Issue by kellery82** [gawindx/homebridge-risco-platform#18]
Hi, my apologies, first time user and am not sure if this is the correct place to log this issue. I've specified ID's 5,6 and 7 as Contact Sensors and 6 is showing up as a Contact Sensor but the others aren't (they are under "3 Contact Sensors" but under accessories, the other two (7 and 8) show up as switches. This is in the latest version and my config is also below - am I doing something stupid or is there an issue?

![image](https://user-images.githubusercontent.com/73224765/96701254-f8948c00-13c2-11eb-9989-4872062af85b.png)

{
    "platform": "RiscoAlarm",
    "name": "Home Alarm",
    "riscoUsername": "USERNAME",
    "riscoPassword": "PASSWORD",
    "riscoSiteId": 12345,
    "riscoPIN": "0000",
    "polling": true,
    "pollInterval": 10000,
    "Partition_Mode": true,
    "armCommand": "armed",
    "partialCommand": "partially",
    "homeCommand": "partially",
    "disarmCommand": "disarmed",
    "Partition": "all",
    "Outputs": "all",
    "Detectors": "5,6,7",
    "Custom": {
        "Contact Sensor": "5,6,7"
    }
}

Log;

[10/21/2020, 5:15:48 PM] [Home Alarm] Contact Sensor "7: Garage Main" => New state detected: (Inactive). Notify!
[10/21/2020, 5:15:48 PM] [Home Alarm] Contact Sensor "7: Garage Main" => New Bypass State detected : (Not ByPassed). Notify!
[10/21/2020, 5:15:49 PM] [Home Alarm] Contact Sensor "8: Garage Rear" => New state detected: (Inactive). Notify!
[10/21/2020, 5:15:49 PM] [Home Alarm] Contact Sensor "8: Garage Rear" => New Bypass State detected : (Not ByPassed). Notify!
[10/21/2020, 5:15:53 PM] [Home Alarm] Adding new accessory with Name: 6: Garage Small, Id: 5, type: Contact Sensor
[10/21/2020, 5:15:53 PM] [Home Alarm] Add or Modifying accessory 6: Garage Small
[10/21/2020, 5:15:53 PM] [Home Alarm] Accessories Init Phase Ended

Also the "Garage Main", "Garage Small" and "Garage Rear" are legitimate Outputs I have.

Thanks in advance

**Comment by kellery82** [comment]
User error - my sensor and output were named the same

**Comment by gawindx** [comment]
no problem

To see your configuration, I see an abnormal point that I did not correctly anticipate.
it is not necessary that you specify the id of your detectors as well in the detectors as in the Custom part.
And, as far as I can remember, this shouldn't work since the id's are already assigned to sensors, it shouldn't be able to be recognized as a Contact.

I will have to specify this point more clearly on the README and check the code because it should not work as is.

do not modify your configuration for the moment, I will get back to you within a few hours to confirm or not the need to modify your configuration.

**Comment by kellery82** [comment]
Thanks for your quick reply. I renamed the outputs on my alarm system already sorry and it seems to have solved the issue;

![8534499A-BA09-4585-9D76-25251C52183A](https://user-images.githubusercontent.com/73224765/96719109-8da37f00-13db-11eb-97a7-7988a4694677.jpeg)
