### ISSUE TITLE
Update not detected. 1.2.0

### ISSUE THREAD

**Issue by kellery82** [gawindx/homebridge-risco-platform#28]
My apologies if this is something I’m doing, but homebridge ui is still showing 1.1.11 as the latest version - 1.2.0 does not show up as an update?

Thanks in advance

**Comment by gawindx** [comment]
This is completely normal.
current version 1.2.0 (the one on github) contains new features such as bundled accessories.

but taking into account the last updates of Risco and the few worries concerning the reconnection, a second version should arrive soon with a major change at the level of the connection to riscocloud.

the modification in question concerns the abandonment of the riscocloud web interface in favor of the use of the Rest API used by the iRisco application.
the main advantages being less use of data, faster data processing (on my side) and especially faster update with the API than through the web interface (and therefore, the homebridge platform).

I still have a lot of development and reverse engineering left because Risco does not document its APIs to the general public.

If you want to test the combined accessories, you can do so but you will have to manually recover the app.js, Risco.js and Riscoaccessories.js files
do not get the package.json file, or modify it to indicate a version lower than 1.2.0, this way the package will update automatically when I release v1.2.0 to npm.

**Comment by kellery82** [comment]
Thanks gawindx, your reply is much appreciated. I apologise for the stupid questions. Also I was looking to see if I could donate something for all your work on the plugin but couldn’t find anything?
