### ISSUE TITLE
DNS hostname nor found???

### ISSUE THREAD

**Issue by platini76** [gawindx/homebridge-risco-platform#34]
[21/12/2020, 04:03:54] [RiscoAlarm] DNS Hostname Not Found. Verify your Internet Connection!!!
[21/12/2020, 04:03:54] [RiscoAlarm] DNS Hostname Not Found. Verify your Internet Connection!!!

what is the problem?

**Comment by gawindx** [comment]
Unfortunately, there is no right answer to your question.
Your internet connection has encountered a problem, whether it is a low bandwidth or simply a DNS server temporarily inaccessible.
If the message is recurrent, it may be a sign of a connection problem or a hardware problem.

At the plugin level itself, this means that the RiscoCloud url has not been resolved by the DNS server, so it is not an error in itself but I report it as such because, the goal being to go to interrogate a server via internet, it seems important to me to inform of a connection problem.

Other error messages can be reported in this way but need not be taken into account if they are not recurrent or persistent.
