### ISSUE TITLE
China Risco

### ISSUE THREAD

**Issue by ChengduKarthago** [gawindx/homebridge-risco-platform#40]
Risco in China is operating a cloned website https://www.riscocloud2.cn/ELAS/WebUI/

It is actually very similar to the original one.

I am wondering if there is a chance to add the support to this website?

**Comment by gawindx** [comment]
in principle this should not be technically impossible provided that:
- the riscockoud in china is at least in v5 (once connected to the web interface, it seems to me that the version number is displayed at the bottom). I specify it because in europe, the copyright is in 2020 while on the link provided, it is from 2014
- know the riscocloud API url, the plugin no longer works with the web interface for some version and I use the same APIs as the iRisco application.
So if the app is not available in China, it might be complicated.

**Comment by gawindx** [comment]
Version 1.2.6 brings support for a new option that will allow you to define a Custom URL.
On the other hand, if the APIs of RiscoCloud in China are not compatible with those available in Europe, it will not work.

**Comment by gawindx** [comment]
This issue is closed due to the stop of the development of the plugin.
For more information, see [here](https://github.com/gawindx/homebridge-risco-platform/issues/45)
